eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: zuul-service
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  eureka:
    enabled: true

server:
  port: 9008
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    api-a:
      path: /api-a/**
      service-id: ribbon
    api-b:
      path: /api-b/**
      service-id: feign
